import images from './images';

const collections = [
    {
        number  : '1',
        imgUrl  : images.gradient_1,
        title   : 'CryptoFunks',
        icon    : images.eth4,
        bid     : '19,763.39',
        percen  : '+26.52%'
    },
    {
        number  : '2',
        imgUrl  : images.gradient_2,
        title   : 'Cryptix',
        icon    : images.eth4,
        bid     : '2,769.39',
        percen  : '+10.52%'
    },
    {
        number  : '3',
        imgUrl  : images.gradient_3,
        title   : 'Frensware',
        icon    : images.eth4,
        bid     : '9,232.39',
        percen  : '+2.52%'
    },
    {
        number  : '4',
        imgUrl  : images.gradient_4,
        title   : 'PunkArt',
        icon    : images.eth4,
        bid     : '3,769.39',
        percen  : '+1.52%'
    },
    {
        number  : '5',
        imgUrl  : images.gradient_5,
        title   : 'Art Crypto',
        icon    : images.eth4,
        bid     : '10,769.39',
        percen  : '+2.52%'
    },
]

const featureds = [
    {
        imgUrl  : images.gradient_1,
        imgUrl2 : images.gradient_5,
        imgUrl3 : images.gradient_4,
        imgUrl4 : images.gradient_2,
        title   : 'Amazing Collection',
        profil  : images.profil,
        names    : 'by Arief Wahyudi',
        item    : 'Total 54 items',
    },
    {
        imgUrl  : images.gradient_4,
        imgUrl2 : images.gradient_1,
        imgUrl3 : images.gradient_7,
        imgUrl4 : images.gradient_6,
        title   : 'Amazing Collection',
        profil  : images.profil,
        names    : 'by Arief Wahyudi',
        item    : 'Total 54 items',
    },
    {
        imgUrl  : images.gradient_6,
        imgUrl2 : images.gradient_2,
        imgUrl3 : images.gradient_5,
        imgUrl4 : images.gradient_6,
        title   : 'Amazing Collection',
        profil  : images.profil,
        names   : 'by Arkhan',
        item    : 'Total 54 items',
    },
] 
const discovers = [
    {
        imgUrl   : images.gradient_1,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_2,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_3,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_4,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_5,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_6,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_7,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_3,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_6,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_2,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_2,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
    {
        imgUrl   : images.gradient_1,
        profil_1 : images.profil,
        profil_2 : images.profil,
        profil_3 : images.profil,
        profil_4 : images.profil,
        title    : 'ArtCrypto',
        icon     : images.eth2,
        bid      : '0.25 ETH',
        amount   : '1 of 321',
        time     : '3h 50m 2s left',
    },
]

export default { collections, featureds,discovers };